FROM bearstech/debian-dev:10

RUN set -eux \
    &&  apt-get update \
    &&  apt-get install -y --no-install-recommends \
            cmake \
            git \
            libjson-c-dev \
            libwebsockets-dev \
            upx \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/* \
    &&  chmod 777 /usr/src

